### ISSUE TITLE
本地启动后，点击登陆按钮时报错

### ISSUE THREAD

**Issue by blue7cat** [fex-team/amis-admin#13]
控制台报错：
Uncaught (in promise) Error: [mobx-state-tree] Only promises can be yielded to async, got: [object Object]
at fail (npm.js:35963)
at next (npm.js:36271)
at onFulfilled (npm.js:36243)

**Comment by catchonme** [comment]
amis@1.0.0.68 版本api验证存在问题，目前已修复，可以使用 amis@1.0.0.70 版本

**Comment by blue7cat** [comment]
谢谢老师，升级到amis@1.0.0-rc.8 就解决了
