### ISSUE TITLE
运行浏览器控制台会出现这个错误提醒：React does not recognize the `activePlacement` prop on a DOM element

### ISSUE THREAD

**Issue by kangxiangzhi** [fex-team/amis-admin#14]
报错情况如下图
![image](https://user-images.githubusercontent.com/18476183/61428022-f4252c00-a952-11e9-9861-dcf500c15f11.png)
npm.js:7760 Warning: React does not recognize the `activePlacement` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activeplacement` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Tooltip)
    in Tooltip (created by Themeable(Tooltip))
    in Themeable(Tooltip) (created by TooltipWrapper)
    in Position (created by Overlay)
    in Portal (created by Overlay)
    in Overlay (created by TooltipWrapper)
    in TooltipWrapper (created by Uncontrolled(TooltipWrapper))
    in Uncontrolled(TooltipWrapper) (created by Themeable(Uncontrolled(TooltipWrapper)))
    in Themeable(Uncontrolled(TooltipWrapper)) (created by Button)
    in Button (created by Themeable(Button))
    in Themeable(Button) (created by Action)
    in Action (created by ButtonRenderer)
    in ButtonRenderer (created by Renderer)
    in Renderer (created by OperationFieldRenderer)
    in div (created by OperationFieldRenderer)
    in OperationFieldRenderer (created by Renderer)
    in Renderer (created by TableCellRenderer)
    in div (created by TableCellRenderer)
    in td (created by TableCellRenderer)
    in TableCellRenderer (created by QuickEditComponent)
    in QuickEditComponent (created by PopOverComponent)
    in PopOverComponent (created by QuickEditComponent)
    in QuickEditComponent (created by Renderer)
    in Renderer (created by TableRow)
    in tr (created by TableRow)
    in TableRow (created by TableRenderer)
    in tbody (created by TableRenderer)
    in table (created by TableRenderer)
    in div (created by TableRenderer)
    in div (created by TableRenderer)
    in div (created by TableRenderer)
    in TableRenderer (created by WithStore(TableRenderer))
    in WithStore(TableRenderer) (created by Renderer)
    in Renderer (created by CRUDRenderer)
    in div (created by CRUDRenderer)
    in CRUDRenderer (created by WithStore(CRUDRenderer))
    in WithStore(CRUDRenderer) (created by Renderer)
    in Renderer (created by PageRenderer)
    in div (created by PageRenderer)
    in div (created by PageRenderer)
    in div (created by PageRenderer)
    in div (created by PageRenderer)
    in PageRenderer (created by WithStore(PageRenderer))
    in WithStore(PageRenderer) (created by Scoped(WithStore(PageRenderer)))
    in Scoped(WithStore(PageRenderer)) (created by Renderer)
    in Renderer (created by RootRenderer)
    in RootRenderer (created by Scoped(RootRenderer))
    in Scoped(RootRenderer) (created by AMisRenderer)
    in AMisRenderer (created by Route)
    in Route (created by withRouter(AMisRenderer))
    in withRouter(AMisRenderer) (created by inject-withRouter(AMisRenderer)-with-store)
    in inject-withRouter(AMisRenderer)-with-store
    in Unknown (created by Route)
    in Route (created by Admin)
    in Switch (created by Admin)
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by Themeable(Layout))
    in Themeable(Layout) (created by Admin)
    in Admin (created by inject-Admin-with-store)
    in inject-Admin-with-store (created by Route)
    in Route (created by _class)
    in Switch (created by _class)
    in div (created by _class)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by _class)
    in _class (created by default_1)
    in Provider (created by default_1)
    in default_1

**Comment by 2betop** [comment]
这个其实可以忽略。

不过，下个版本会修复，参考：https://github.com/baidu/amis/commit/f590561c59adccf05c122ccc32121ee2d20e1e39

**Comment by kangxiangzhi** [comment]
好的，感谢解答
