### ISSUE TITLE
新手npm start遇到的问题：Cannot find module 'node_modules/path/path'

### ISSUE THREAD

**Issue by kangxiangzhi** [fex-team/amis-admin#15]
![image](https://user-images.githubusercontent.com/18476183/61435256-aae0d680-a96a-11e9-9418-b86b64106b0f.png)
![image](https://user-images.githubusercontent.com/18476183/61435280-b502d500-a96a-11e9-9065-b73f8758d20a.png)
 把这个改成 const path = require('path'); 就好了，这个是要配置什么环境变量吗？

**Comment by 2betop** [comment]
git pull 吧，之前为了公用 mock，改了下编译配置，现在还原了

**Comment by kangxiangzhi** [comment]
好的，非常感谢
