### ISSUE TITLE
线上环境报错：isCancel未实现

### ISSUE THREAD

**Issue by buchongyu** [fex-team/amis-admin#17]
@ owner沟通.
isCancel  函数未实现。
修改：amis-fe/App.tsx
![image](https://user-images.githubusercontent.com/8272958/61576694-b28db000-ab0f-11e9-9558-76ddb415e4fa.png)

**Comment by buchongyu** [comment]
![image](https://user-images.githubusercontent.com/8272958/61576708-d4873280-ab0f-11e9-98de-3105f766dd9f.png)

**Comment by 2betop** [comment]
已经提交哈
