### ISSUE TITLE
新手部署问题

### ISSUE THREAD

**Issue by kangxiangzhi** [fex-team/amis-admin#18]
可以给一下fis3打包生产环境的配置吗？

通过fis3 release gh-pages -c 这个命令 打包出来的东西，我发现所有的html界面都是一样的，不是很明白该用什么web server来部署，nginx 我试了一下不行。

可以给一下 部署的流程吗？

**Comment by 2betop** [comment]
把这个干掉就行了 https://github.com/fex-team/amis-admin/blob/master/fis-conf.js#L174-L191

**Comment by kangxiangzhi** [comment]
感谢
