### ISSUE TITLE
AsideNav怎么实现多层级？

### ISSUE THREAD

**Issue by FatDong1** [fex-team/amis-admin#21]
可以提供一个三层的demo吗

**Comment by FatDong1** [comment]
![image](https://user-images.githubusercontent.com/22772600/62850197-b4b0ec00-bd14-11e9-8e37-8a15462e4dcd.png)
这三级的点击都是命中黄色箭头的组件

**Comment by FatDong1** [comment]
hash模式

**Comment by FatDong1** [comment]
![image](https://user-images.githubusercontent.com/22772600/62860869-2ea49d80-bd34-11e9-81cc-167f80911482.png)

**Comment by FatDong1** [comment]
试了一下，发现如果路由不嵌套是可以多层级的
比如下面这样的路由就可以
```bash
/admin/form
/admin/basic
/admin/test
```

**Comment by 2betop** [comment]
参考 https://github.com/fex-team/amis-admin/commit/9181039a56f0ca3707559f93c675dcbeaecf6808

**Comment by FatDong1** [comment]
非常感谢
