### ISSUE TITLE
请问有计划支持热更新吗？

### ISSUE THREAD

**Issue by ly525** [fex-team/amis-admin#28]
您好，首先感谢 amis 这么优秀的项目。

我在本地开发时候，有一个小疑惑：
在 clone 项目之后，npm start 之后，本地改了代码，浏览器并没有自动刷新，需要手动刷新。请问这个需要安装插件或者进行其它额外配置吗？

非常感谢

**Comment by 2betop** [comment]
这个依赖 fis3， fis3 没有 hot reload, 但是有 live reload 具体怎么搞还要去看 fis3 相关的文档了。

**Comment by ly525** [comment]
> 这个依赖 fis3， fis3 没有 hot reload, 但是有 live reload 具体怎么搞还要去看 fis3 相关的文档了。

好嘞，非常感谢。我去看看
