### ISSUE TITLE
 RichText.js TypeError: init is not a function

### ISSUE THREAD

**Issue by babulongbo007** [fex-team/amis-admin#35]
执行：
 git clone https://github.com/fex-team/amis-admin.git
 
 git checkout webpack
 
 npm i
 
 修改Dashboard.tsx
` import schema2component from "../../utils/schema2component";

	const schema = {
		type: 'page',
		title: 'Dashboard',
		body: {
			type: "form",
			mode: "horizontal",
			controls: [
				{
					type: 'rich-text',
					name: "html",
					label: "Rich Text"
				}
			]
		}
	};

	export default schema2component(schema);`
	复现问题

**Comment by 2betop** [comment]
咋又开了？

**Comment by babulongbo007** [comment]
我看这个问题关闭了，但是我直接在将代码克隆到本地，发现问题依然存在

**Comment by 2betop** [comment]
https://github.com/baidu/amis/issues/489

**Comment by babulongbo007** [comment]
是我执行的步骤有问题吗

**Comment by 2betop** [comment]
要pull 代码啊
或者手动加上，那个 diff https://github.com/fex-team/amis-admin/commit/8cc73ae123e33ad1ec577f2605ea4b7d066bca3e

**Comment by babulongbo007** [comment]
可能我没说清楚我执行的步骤:
 git clone https://github.com/fex-team/amis-admin.git
 
 git checkout webpack

 git reset --hard origin/webpack
 
 npm i
修改Dashboard.tsx
-----------------------------------------------------------------------------------
现在我使用git diff,除了Dashboard.tsx文件修改的内容，其他的一致。
**然后本地依然出错**

**Comment by babulongbo007** [comment]
![image](https://user-images.githubusercontent.com/31446640/76588146-35d99700-6521-11ea-9d95-8d60b826722f.png)

**Comment by babulongbo007** [comment]
![image](https://user-images.githubusercontent.com/31446640/76588191-5a357380-6521-11ea-937d-15d41ed486c3.png)

**Comment by babulongbo007** [comment]
![image](https://user-images.githubusercontent.com/31446640/76588207-6c171680-6521-11ea-8b0a-7f7f5f28d419.png)

**Comment by babulongbo007** [comment]
![image](https://user-images.githubusercontent.com/31446640/76588300-a84a7700-6521-11ea-9589-d365a725707d.png)
![image](https://user-images.githubusercontent.com/31446640/76588333-b7c9c000-6521-11ea-887d-0d4a81d07207.png)

**Comment by babulongbo007** [comment]
![image](https://user-images.githubusercontent.com/31446640/76588685-8f8e9100-6522-11ea-9411-8f193713cc75.png)

**Comment by 2betop** [comment]
那不可能吧，我昨天就是加了这个配置后，就能跑了。

**Comment by babulongbo007** [comment]
那你运行的开发环境还是生产环境

**Comment by 2betop** [comment]
我还没加生产环境的配置，就是 `npm start`

**Comment by babulongbo007** [comment]
你是在Linux环境运行的还是window环境运行

**Comment by 2betop** [comment]
mac , 跟这个应该没关系吧。我这 webpack 版本是 `webpack@4.41.5` 你对比一下你的

**Comment by babulongbo007** [comment]
版本确实不一样，能否将项目的package-lock.json文件发出来，我这边每次安装时，版本和package.json文件不一致

**Comment by babulongbo007** [comment]
![image](https://user-images.githubusercontent.com/31446640/76593538-92dd4900-6531-11ea-8f94-43c63d98b05f.png)

![image](https://user-images.githubusercontent.com/31446640/76593442-498cf980-6531-11ea-920e-37c5b760d45e.png)
![image](https://user-images.githubusercontent.com/31446640/76593526-80fba600-6531-11ea-968f-23e200d9ddfc.png)

我把node_modules/和package-lock.json删除后，然后锁死版本进行npm install，但是依然不可以

**Comment by 2betop** [comment]
我猜估计是那个 test 后面的 `\/` 有问题，删了试试，估计是因为 window 的路径 `\\` 的原因

**Comment by babulongbo007** [comment]
![image](https://user-images.githubusercontent.com/31446640/76726001-ded6fa80-678a-11ea-88a5-7e541eaa86ba.png)
![image](https://user-images.githubusercontent.com/31446640/76726008-e5fe0880-678a-11ea-9bb3-b3bdd0ea14c8.png)
确实是webpack配置的路径问题，非常感谢
