### ISSUE TITLE
使用chart时报错

### ISSUE THREAD

**Issue by Angel888** [fex-team/amis-admin#37]
代码：
```
{
            type: "chart",
            name: "chart3",
            initFetch: true,
            api: "http://xxx.com?action_type=pie_chart",
        }
```
consolo报错：
```
factory.js:459 Please implements this. see https://baidu.github.io/amis/docs/getting-started#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8
isCancel @ factory.js:459
(anonymous) @ Chart.js:131
```
主要问题是，会有一个警告的弹框：is cancel, 图可以正确显示。

**Comment by Angel888** [comment]
<img width="336" alt="截屏2020-03-28 下午8 59 52" src="https://user-images.githubusercontent.com/22865550/77823590-2c624880-7137-11ea-89ed-572d1af9cb88.png">

**Comment by 2betop** [comment]
可能是没有在 env 处传入 isCancel 这个吧。

**Comment by 2betop** [comment]
把这个传入试试

![image](https://user-images.githubusercontent.com/2698393/77824021-48b3b480-713a-11ea-95b2-1c49988b2e51.png)

**Comment by Angel888** [comment]
谢谢，
代码里加了 `isCancel: (e:any) => axios.isCancel(e),`
webpack版本，改成
![](https://user-images.githubusercontent.com/2698393/77824021-48b3b480-713a-11ea-95b2-1c49988b2e51.png)
这样也不行
fis3版本，不需要修改也没有报错。
我还是先用fis3了

**Comment by Taaang** [comment]
遇到相同问题无法解决，确认env里传入了isCancel，求解
