### ISSUE TITLE
为什么我用fis3或webpack打出来的包，js有14M左右，github上的demo只有几百k，如何做到的？

### ISSUE THREAD

**Issue by Angel888** [fex-team/amis-admin#38]
<img width="1434" alt="截屏2020-03-28 下午9 03 10" src="https://user-images.githubusercontent.com/22865550/77823632-92e76680-7137-11ea-90c8-5c72b6f27a25.png">

尽管我用了terser-webpack-plugin，还是有十几兆
<img width="1433" alt="截屏2020-03-28 下午9 05 17" src="https://user-images.githubusercontent.com/22865550/77823677-da6df280-7137-11ea-9520-f3989d59d3a7.png">

顺带问一下，为啥页面状态是404，但是可以正常访问，前端小白，求指教！

**Comment by 2betop** [comment]
fis3 上的配置 https://github.com/fex-team/amis-admin/blob/master/fis-conf.js#L141-L226

主要是压缩和打包

**Comment by 2betop** [comment]
另外那些比较大的编辑器 manaco-editor rich-text chearts 之类的单独打包了，用的时候再按需加载。

**Comment by Angel888** [comment]
<img width="1047" alt="截屏2020-03-28 下午10 41 17" src="https://user-images.githubusercontent.com/22865550/77825654-a699c980-7145-11ea-8427-c29916f5dcae.png">
直接拉master代码，运行npm run gh-pages 会报错，不知道什么原因。
node 版本：10.18.0
系统：mac os

npm run dev
一样报错

**Comment by Angel888** [comment]
linux中运行npm run gh-pages  可以编译成功，但是访问时，报错：
Uncaught [ModJS] Cannot find module `node_modules/react-datetime/css/react-datetime.css`

**Comment by 2betop** [comment]
喔，补一个

```
fis.match('amis/**.js', {
  preprocessor: fis.plugin('js-require-css')
});
```

**Comment by Angel888** [comment]
谢谢，可以了。
