### ISSUE TITLE
侧边栏可以传递query_params参数吗？

### ISSUE THREAD

**Issue by zhangyucumt** [fex-team/amis-admin#44]

**Comment by zhangyucumt** [comment]
就是侧边栏可以变成 
| - 目录
    | - aa/bb?id=1
    | - aa/bb?id=2
    | - aa/bb?id=3
就是对应的组件是同一个组件  只有传递的params不一样

**Comment by 2betop** [comment]
自己动手试试就知道了
https://github.com/fex-team/amis-admin/blob/master/routes/admin/index.tsx#L106

**Comment by zhangyucumt** [comment]
已解决~

**Comment by 84896150** [comment]
> 已解决~

请问怎么解决的呢？

**Comment by zhangyucumt** [comment]
> > 已解决~
> 
> 请问怎么解决的呢？

时间太久了 好久没用这个package了  sorry
